name: "Release"

on:
  workflow_dispatch:
    inputs:
      increaseMajor:
        description: "Increase major version"
        type: boolean
        required: false

jobs:
  create-branch:
    uses: kumahq/.github/.github/workflows/release.yaml@main
    with:
      increaseMajor: ${{ github.event.inputs.increaseMajor == 'true' }}
